[package]
name = "cert-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file-io = { path = "../libs/file-io" }
rcgen = "0.10"
clap = "4.1"
