[workspace]

members = [
  "world",
  "worker",
  "controller",
  "cert-gen",
  "custom_macro",
  "libs/api",
  "libs/world-if",
  "libs/worker-if",
  "libs/protocol",
  "libs/file-io",
  "libs/quic-config",
  "libs/repl",
  "libs/table",
]
