[workspace]

members = [
  "world",
  "container",
  "controller",
  "api-server",
  "cert-gen",
  "custom_macro",
  "libs/world-if",
  "libs/container-if",
  "libs/protocol",
  "libs/batch",
  "libs/file-io",
  "libs/quic-config",
  "libs/repl",
  "libs/table",
]
