[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
container-if = {path = "../container-if"}
protocol = {path = "../protocol"}
world-if = {path = "../world-if"}
argopt = "0.3"
peg = "0.8"