[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
container-if = { path = "../libs/container-if" }
protocol = { path = "../libs/protocol" }
world-if = { path = "../libs/world-if" }
quic-config = { path = "../libs/quic-config" }
repl = { path = "../libs/repl" }
async-trait = "0.1"
argopt = "0.3"
quinn = "0.9"
rustls = "0.20"
tokio = { version = "1.21", features = ["full"] }
parking_lot = "0.12"
ulid = "1"
batch = { path = "../libs/batch" }
